[rewrite_local]
# ==========================================
# Header Rewrites (移除 RevenueCat 的 ETag)
# ==========================================
^https?:\/\/api\.revenuecat\.com\/.+\/(receipts|subscribers) url request-header (\r\n)X-RevenueCat-ETag:.* request-header $1
^https?:\/\/api\.revenuecat\.com\/.+\/(receipts|subscribers) url request-header (\r\n)x-revenuecat-etag:.* request-header $1

# ==========================================
# Scriptings (JS 脚本注入)
# ==========================================
# AppRCTesters
^https?:\/\/api\.revenuecat\.com\/.+\/(receipts|subscribers) url script-response-body AutoRC.js

# AppAdTesters
^https?:\/\/api\.adapty\.io\/api\/v1\/sdk\/analytics\/profiles url script-response-body Adapty.js

# AppFMTesters
^https?:\/\/order\.creativeappnow\.com\/iap\/receipt url script-response-body Facemoji.js

# AppReTesters
^https?:\/\/license\.pdfexpert\.com\/api\/2\.0\/(calendarslite|pdfexpert6|documents)\/subscription\/(refresh|check) url script-response-body readdle.js

# AppitTesters
^https?:\/\/buy\.itunes\.apple\.com\/verifyReceipt url script-response-body iTunes.js

# AppMuTesters
^https?:\/\/us-central1-muslim-pro-app\.cloudfunctions\.net\/GetUserPremiumInfo url script-response-body MuslimPro.js

# AppGrTesters
^https?:\/\/subscription\.grammarly\.com\/api\/v1\/subscription$ url script-response-body Grammarly.js

# AppeSTesters
^https?:\/\/api\.esound\.app\/account url script-response-body eSound.js

# AppPurTesters
^https?:\/\/api\.purchasely\.io\/paab\/user_purchases url script-response-body purchasely.js

# AppVaTesters
^https?:\/\/prod\.studysmarter\.de\/payments\/info url script-response-body Vaia.js

# AppQOTesters
^https?:\/\/api\.qonversion\.io\/v1\/user\/init url script-response-body qonversion.js

# AppDJTesters
^https?:\/\/api\.mwm-users\.com\/me\/features url script-response-body edjingMix.js

# AppVCTesters
^https?:\/\/api-fra\.vivacut\.com\/api\/rest\/commerce\/integrate\/vip\/perform url script-response-body VivaCut.js

# AppCaTesters
^https?:\/\/carrotweather\.herokuapp\.com\/parse\/functions\/findSubscriptionsForUserId url script-response-body Carrot.js

# AppKineTesters
^https?:\/\/api-account\.kinemasters\.com\/v2\/user\/subscribe url script-response-body KineMaster.js

# AppPicTesters
^https?:\/\/api\.picsart\.com\/gw-v2\/shop\/subscription\/apple\/purchases url script-request-body PicsArt.js

# AppAMTesters
^https?:\/\/us-central1-alight-creative\.cloudfunctions\.net\/getAccountStatusAndLicenses url script-response-body AlightMotion.js

# AppSaTesters
^https?:\/\/api\.sandbox\.love\/accounts\/current url script-response-body SandBox.js

# AppSSesters
^https?:\/\/subscriptions\.songshift\.com\/validate url script-response-body SongShift.js

# AppADBTesters
^https?:\/\/api\.adblockpro\.app\/verify url script-response-body AdblockPro.js

# AppADGTesters
^https?:\/\/mobile-api\.adguard\.org\/api\/.+\/ios_validate_receipt\/.* url script-response-body AdGuardPro.js

# AppDTesters
^https?:\/\/ILoveDevTheDev\.com url script-response-body URL2Script.js


[mitm]
hostname = api.revenuecat.com, buy.itunes.apple.com, api.picsart.com, api-account.kinemasters.com, us-central1-alight-creative.cloudfunctions.net, api.adapty.io, carrotweather.herokuapp.com, order.creativeappnow.com, api.mwm-users.com, us-central1-muslim-pro-app.cloudfunctions.net, prod.studysmarter.de, api.qonversion.io, subscription.grammarly.com, api.esound.app, api.purchasely.io, api.sandbox.love, subscriptions.songshift.com, api.adblockpro.app, mobile-api.adguard.org, license.pdfexpert.com, api-fra.vivacut.com, ILoveDevTheDev.com
