# ==========================================
# Header Rewrites (移除 RevenueCat 的 ETag)
# ==========================================
^https?:\/\/api\.revenuecat\.com\/.+\/(receipts|subscribers) url request-header (\r\n)X-RevenueCat-ETag:.* request-header $1
^https?:\/\/api\.revenuecat\.com\/.+\/(receipts|subscribers) url request-header (\r\n)x-revenuecat-etag:.* request-header $1

# ==========================================
# Scriptings (JS 脚本注入)
# ==========================================
^https?:\/\/api\.revenuecat\.com\/.+\/(receipts|subscribers) url script-response-body https://apptesters.org/egern/AutoRC.js
^https?:\/\/api\.adapty\.io\/api\/v1\/sdk\/analytics\/profiles url script-response-body https://apptesters.org/egern/Adapty.js
^https?:\/\/order\.creativeappnow\.com\/iap\/receipt url script-response-body https://apptesters.org/egern/Facemoji.js
^https?:\/\/license\.pdfexpert\.com\/api\/2\.0\/(calendarslite|pdfexpert6|documents)\/subscription\/(refresh|check) url script-response-body https://apptesters.org/egern/readdle.js
^https?:\/\/buy\.itunes\.apple\.com\/verifyReceipt url script-response-body https://apptesters.org/egern/iTunes.js
^https?:\/\/us-central1-muslim-pro-app\.cloudfunctions\.net\/GetUserPremiumInfo url script-response-body https://apptesters.org/egern/MuslimPro.js
^https?:\/\/subscription\.grammarly\.com\/api\/v1\/subscription$ url script-response-body https://apptesters.org/egern/Grammarly.js
^https?:\/\/api\.esound\.app\/account url script-response-body https://apptesters.org/egern/eSound.js
^https?:\/\/api\.purchasely\.io\/paab\/user_purchases url script-response-body https://apptesters.org/egern/purchasely.js
^https?:\/\/prod\.studysmarter\.de\/payments\/info url script-response-body https://apptesters.org/egern/Vaia.js
^https?:\/\/api\.qonversion\.io\/v1\/user\/init url script-response-body https://apptesters.org/egern/qonversion.js
^https?:\/\/api\.mwm-users\.com\/me\/features url script-response-body https://apptesters.org/egern/edjingMix.js
^https?:\/\/api-fra\.vivacut\.com\/api\/rest\/commerce\/integrate\/vip\/perform url script-response-body https://apptesters.org/egern/VivaCut.js
^https?:\/\/carrotweather\.herokuapp\.com\/parse\/functions\/findSubscriptionsForUserId url script-response-body https://apptesters.org/egern/Carrot.js
^https?:\/\/api-account\.kinemasters\.com\/v2\/user\/subscribe url script-response-body https://apptesters.org/egern/KineMaster.js
^https?:\/\/api\.picsart\.com\/gw-v2\/shop\/subscription\/apple\/purchases url script-request-body https://apptesters.org/egern/PicsArt.js
^https?:\/\/us-central1-alight-creative\.cloudfunctions\.net\/getAccountStatusAndLicenses url script-response-body https://apptesters.org/egern/AlightMotion.js
^https?:\/\/api\.sandbox\.love\/accounts\/current url script-response-body https://apptesters.org/egern/SandBox.js
^https?:\/\/subscriptions\.songshift\.com\/validate url script-response-body https://apptesters.org/egern/SongShift.js
^https?:\/\/api\.adblockpro\.app\/verify url script-response-body https://apptesters.org/egern/AdblockPro.js
^https?:\/\/mobile-api\.adguard\.org\/api\/.+\/ios_validate_receipt\/.* url script-response-body https://apptesters.org/egern/AdGuardPro.js
^https?:\/\/ILoveDevTheDev\.com url script-response-body https://URL2Script.com
